// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_rmvnorm
arma::mat fast_rmvnorm(int n, const arma::mat& L);
RcppExport SEXP _mainger_fast_rmvnorm(SEXP nSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rmvnorm(n, L));
    return rcpp_result_gen;
END_RCPP
}
// fast_gram
arma::mat fast_gram(const arma::mat& X);
RcppExport SEXP _mainger_fast_gram(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_gram(X));
    return rcpp_result_gen;
END_RCPP
}
// fast_xty
arma::vec fast_xty(const arma::mat& X, const arma::vec& Y);
RcppExport SEXP _mainger_fast_xty(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_xty(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// fast_ridge_solve
arma::vec fast_ridge_solve(const arma::mat& A, const arma::vec& b, double lambda);
RcppExport SEXP _mainger_fast_ridge_solve(SEXP ASEXP, SEXP bSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ridge_solve(A, b, lambda));
    return rcpp_result_gen;
END_RCPP
}
// fast_mv
arma::vec fast_mv(const arma::mat& X, const arma::vec& beta);
RcppExport SEXP _mainger_fast_mv(SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_mv(X, beta));
    return rcpp_result_gen;
END_RCPP
}
// fast_pred_r2
double fast_pred_r2(const arma::vec& Y_true, const arma::vec& Y_pred);
RcppExport SEXP _mainger_fast_pred_r2(SEXP Y_trueSEXP, SEXP Y_predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_true(Y_trueSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_pred(Y_predSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_pred_r2(Y_true, Y_pred));
    return rcpp_result_gen;
END_RCPP
}
// fast_mspe
double fast_mspe(const arma::vec& Y_true, const arma::vec& Y_pred);
RcppExport SEXP _mainger_fast_mspe(SEXP Y_trueSEXP, SEXP Y_predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_true(Y_trueSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_pred(Y_predSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_mspe(Y_true, Y_pred));
    return rcpp_result_gen;
END_RCPP
}
// fast_eta_search
List fast_eta_search(const arma::vec& beta_int, const arma::vec& theta_ext, const arma::mat& X_val, const arma::vec& Y_val, const arma::vec& eta_grid);
RcppExport SEXP _mainger_fast_eta_search(SEXP beta_intSEXP, SEXP theta_extSEXP, SEXP X_valSEXP, SEXP Y_valSEXP, SEXP eta_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_int(beta_intSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_ext(theta_extSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_val(X_valSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_val(Y_valSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_grid(eta_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_eta_search(beta_int, theta_ext, X_val, Y_val, eta_grid));
    return rcpp_result_gen;
END_RCPP
}
// run_one_rep
List run_one_rep(const arma::mat& L_pop, const arma::vec& beta_int, const arma::vec& beta_ext, double sigma2, int n_int, int n_ext, int n_ref, int n_test, double lambda_ridge, double lambda_ext, const arma::vec& eta_grid, int n_val);
RcppExport SEXP _mainger_run_one_rep(SEXP L_popSEXP, SEXP beta_intSEXP, SEXP beta_extSEXP, SEXP sigma2SEXP, SEXP n_intSEXP, SEXP n_extSEXP, SEXP n_refSEXP, SEXP n_testSEXP, SEXP lambda_ridgeSEXP, SEXP lambda_extSEXP, SEXP eta_gridSEXP, SEXP n_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L_pop(L_popSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_int(beta_intSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_ext(beta_extSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type n_int(n_intSEXP);
    Rcpp::traits::input_parameter< int >::type n_ext(n_extSEXP);
    Rcpp::traits::input_parameter< int >::type n_ref(n_refSEXP);
    Rcpp::traits::input_parameter< int >::type n_test(n_testSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_ridge(lambda_ridgeSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_ext(lambda_extSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_grid(eta_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_val(n_valSEXP);
    rcpp_result_gen = Rcpp::wrap(run_one_rep(L_pop, beta_int, beta_ext, sigma2, n_int, n_ext, n_ref, n_test, lambda_ridge, lambda_ext, eta_grid, n_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mainger_fast_rmvnorm", (DL_FUNC) &_mainger_fast_rmvnorm, 2},
    {"_mainger_fast_gram", (DL_FUNC) &_mainger_fast_gram, 1},
    {"_mainger_fast_xty", (DL_FUNC) &_mainger_fast_xty, 2},
    {"_mainger_fast_ridge_solve", (DL_FUNC) &_mainger_fast_ridge_solve, 3},
    {"_mainger_fast_mv", (DL_FUNC) &_mainger_fast_mv, 2},
    {"_mainger_fast_pred_r2", (DL_FUNC) &_mainger_fast_pred_r2, 2},
    {"_mainger_fast_mspe", (DL_FUNC) &_mainger_fast_mspe, 2},
    {"_mainger_fast_eta_search", (DL_FUNC) &_mainger_fast_eta_search, 5},
    {"_mainger_run_one_rep", (DL_FUNC) &_mainger_run_one_rep, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_mainger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
