# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_rmvnorm <- function(n, L) {
    .Call('_mainger_fast_rmvnorm', PACKAGE = 'mainger', n, L)
}

fast_gram <- function(X) {
    .Call('_mainger_fast_gram', PACKAGE = 'mainger', X)
}

fast_xty <- function(X, Y) {
    .Call('_mainger_fast_xty', PACKAGE = 'mainger', X, Y)
}

fast_ridge_solve <- function(A, b, lambda) {
    .Call('_mainger_fast_ridge_solve', PACKAGE = 'mainger', A, b, lambda)
}

fast_mv <- function(X, beta) {
    .Call('_mainger_fast_mv', PACKAGE = 'mainger', X, beta)
}

fast_pred_r2 <- function(Y_true, Y_pred) {
    .Call('_mainger_fast_pred_r2', PACKAGE = 'mainger', Y_true, Y_pred)
}

fast_mspe <- function(Y_true, Y_pred) {
    .Call('_mainger_fast_mspe', PACKAGE = 'mainger', Y_true, Y_pred)
}

fast_eta_search <- function(beta_int, theta_ext, X_val, Y_val, eta_grid) {
    .Call('_mainger_fast_eta_search', PACKAGE = 'mainger', beta_int, theta_ext, X_val, Y_val, eta_grid)
}

run_one_rep <- function(L_pop, beta_int, beta_ext, sigma2, n_int, n_ext, n_ref, n_test, lambda_ridge, lambda_ext, eta_grid, n_val) {
    .Call('_mainger_run_one_rep', PACKAGE = 'mainger', L_pop, beta_int, beta_ext, sigma2, n_int, n_ext, n_ref, n_test, lambda_ridge, lambda_ext, eta_grid, n_val)
}

